-- SurfHub Schema: Profiles & Amenity Ratings
-- Run: supabase db push or paste in Supabase SQL Editor

-- ─── PROFILES ────────────────────────────────────────────────
-- Extends auth.users with surfer-specific profile data

create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  username    text unique,
  full_name   text,
  avatar_url  text,
  website     text,
  about       text,
  home_break  text,          -- their local surf spot
  surf_level  text           -- beginner | intermediate | advanced | pro
    check (surf_level in ('beginner', 'intermediate', 'advanced', 'pro')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- Users can read any profile (directory feature)
create policy "Profiles are publicly readable"
  on public.profiles for select
  using (true);

-- Users can insert their own profile
create policy "Users can insert their own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

-- Users can update their own profile
create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- ─── AMENITY RATINGS ─────────────────────────────────────────
-- Each user can rate an amenity once (1-5 stars)
-- Separate table so we can aggregate + verify

create table if not exists public.amenity_ratings (
  id          bigint generated by default as identity primary key,
  amenity_id  text not null,          -- references amenity id from amenities data
  user_id     uuid not null references auth.users(id) on delete cascade,
  rating      smallint not null check (rating >= 1 and rating <= 5),
  verified    boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  -- One rating per user per amenity
  unique(amenity_id, user_id)
);

alter table public.amenity_ratings enable row level security;

-- Anyone can read ratings (for displaying averages)
create policy "Ratings are publicly readable"
  on public.amenity_ratings for select
  using (true);

-- Authenticated users can insert their own ratings
create policy "Users can insert their own ratings"
  on public.amenity_ratings for insert
  with check (auth.uid() = user_id);

-- Users can update their own ratings
create policy "Users can update their own ratings"
  on public.amenity_ratings for update
  using (auth.uid() = user_id);

-- Users can delete their own ratings
create policy "Users can delete their own ratings"
  on public.amenity_ratings for delete
  using (auth.uid() = user_id);

-- ─── INDEXES ─────────────────────────────────────────────────
create index if not exists idx_amenity_ratings_amenity
  on public.amenity_ratings(amenity_id);
create index if not exists idx_amenity_ratings_user
  on public.amenity_ratings(user_id);

-- ─── TRIGGER: auto-update updated_at ────────────────────────
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create or replace trigger on_profiles_updated
  before update on public.profiles
  for each row execute function public.handle_updated_at();

create or replace trigger on_amenity_ratings_updated
  before update on public.amenity_ratings
  for each row execute function public.handle_updated_at();
